import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Login from './Login/page'
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
import ProjectCard from "./components/ProjectCard";
import TaskCard from "./components/TaskCard";
import TaskColumn from "./components/TaskColumn";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Criando Componentes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
               <Login/>
      </body>
    </html>
  );
}
